repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: local
    hooks:
    -   id: black
        name: black
        language: python
        entry: black
        types: [python]

    -   id: autoflake
        name: autoflake
        entry: >-
          autoflake
          --in-place
          --remove-all-unused-imports
          --remove-unused-variables
        language: python
        types: [python]

    -   id: flake8
        name: flake8
        language: system
        entry: >-
          flake8
          --max-line-length=150
          --ignore=F403,F405,F841,W503
        types: [python]

-   repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
       -   id: isort
           name: isort (python)

-   repo: https://github.com/pycqa/pydocstyle
    rev: 4.0.0  # pick a git hash / tag to point to
    hooks:
    -   id: pydocstyle
        args:
          -   --ignore=D203, D212, D213, D406, D407, D413, D417
